version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    entrypoint: /bin/sh /code/commons/scripts/entrypoint.sh
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - db
    stdin_open: true
    tty: true
  nginx:
    build: ./commons/conf/nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
