version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    entrypoint: /bin/sh /code/commons/scripts/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  letsencrypt:
    image: linuxserver/letsencrypt
    ports:
      - 80:8000
      - 443:443
    volumes:
      - ./config/letsencrypt:/config
    environment:
      - EMAIL=admin@tandora.co
      - URL=localhost
      - SUBDOMAINS=www,api
      - ONLY_SUBDOMAINS=true
      - VALIDATION=http
      - TZ=Asia/Kolkata
      - PUID=1000
      - PGID=1000
    depends_on:
      - web

volumes:
  postgres_data:
