# Generated by Django 2.1.5 on 2019-08-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('db_name', models.CharField(max_length=110, unique=True)),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=50)),
                ('db_host', models.CharField(max_length=20)),
                ('db_port', models.CharField(default=5432, max_length=4)),
                ('subdomain', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'master_instance_details',
            },
        ),
    ]
