# Generated by Django 2.1.5 on 2019-10-03 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='embed',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.Company'),
        ),
    ]
