# Generated by Django 2.1.5 on 2019-03-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(default='', unique=True),
            preserve_default=False,
        ),
    ]
