# Generated by Django 2.1.5 on 2019-04-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_company_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'color')},
        ),
    ]
