# Generated by Django 2.1.5 on 2019-04-11 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20190411_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
