# Generated by Django 2.1.5 on 2019-10-08 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20191008_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_superuser',
        ),
    ]
