# Generated by Django 2.1.5 on 2019-04-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_auto_20190414_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='changelog_terminology',
            field=models.CharField(default='Changelog', max_length=50),
        ),
    ]
