# Generated by Django 2.1.5 on 2019-10-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20191009_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_trial_account',
            field=models.BooleanField(default=False),
        ),
    ]
