# Generated by Django 2.1.5 on 2019-05-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
