# Generated by Django 2.1.5 on 2019-11-01 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_company_is_trial_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monthly_price', models.FloatField()),
                ('yearly_price', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('plan_features', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_yearly', models.BooleanField(default=True)),
                ('razorpay_account_id', models.CharField(max_length=50)),
                ('razorpay_data', models.TextField()),
                ('last_paid_time', models.DateTimeField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.PricePlan')),
            ],
        ),
    ]
