# Generated by Django 2.1.5 on 2019-11-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_priceplan_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.Company'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.PricePlan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='razorpay_account_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
