# Generated by Django 2.1.5 on 2019-05-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_auto_20190504_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('hide_from_crawlers', models.BooleanField(default=False)),
                ('show_authors', models.BooleanField(default=False)),
                ('private_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
