# Generated by Django 2.1.5 on 2019-05-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_publicpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.TextField(blank=True)),
                ('javascript', models.TextField(blank=True)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
    ]
