# Generated by Django 2.1.5 on 2019-11-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_angeluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='last_paid_time',
            field=models.DateTimeField(null=True),
        ),
    ]
