# Generated by Django 2.1.5 on 2019-05-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_embed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name=254)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
