# Generated by Django 2.1.5 on 2019-11-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_auto_20191102_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='forgotpassword',
            unique_together={('email', 'created_date')},
        ),
    ]
