# Generated by Django 2.1.5 on 2019-11-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_auto_20191104_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_trial_account',
            field=models.BooleanField(default=True),
        ),
    ]
