# Generated by Django 2.1.5 on 2019-06-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_clienttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
