# Generated by Django 2.1.5 on 2019-11-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_auto_20191121_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('why', models.TextField()),
            ],
        ),
    ]
