# Generated by Django 2.1.5 on 2019-06-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_changelog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
