# Generated by Django 2.1.5 on 2019-11-30 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0014_affiliate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('conversion_count', models.PositiveIntegerField(default=0)),
                ('company_ids', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='affiliate',
            old_name='company_name',
            new_name='qualification',
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.Affiliate'),
        ),
    ]
