# Generated by Django 2.1.5 on 2019-06-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0014_auto_20190615_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
