# Generated by Django 2.1.5 on 2019-07-23 15:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0015_auto_20190616_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
