# Generated by Django 2.1.5 on 2019-12-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0015_auto_20191130_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='use_case',
            field=models.CharField(choices=[('c', 'Publishing product updates, changelog or blog'), ('s', 'Static site')], default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='referral',
            name='company_ids',
            field=models.TextField(default='{}'),
        ),
    ]
