# Generated by Django 2.1.5 on 2019-12-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_auto_20191210_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='_settings',
            field=models.TextField(blank=True, db_column='settings', null=True),
        ),
    ]
