# Generated by Django 2.1.5 on 2019-12-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0017_company__settings'),
        ('v1', '0018_auto_20191212_0336'),
    ]

    operations = [
    ]
