# Generated by Django 2.1.5 on 2019-12-14 03:40

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0019_merge_20191213_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticSiteField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('c', 'char'), ('t', 'text'), ('u', 'link')], max_length=2)),
                ('required', models.BooleanField(default=False)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaticSiteTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('template_file', models.CharField(blank=True, max_length=100, null=True)),
                ('template_content', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaticSiteThemeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.ManyToManyField(to='v1.StaticSiteField')),
                ('theme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.StaticSiteTheme')),
            ],
        ),
    ]
