# Generated by Django 2.1.5 on 2019-12-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0020_staticsitefield_staticsitetheme_staticsitethemeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticsitetheme',
            name='template_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
