# Generated by Django 2.1.5 on 2020-01-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0021_auto_20191214_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticsitefield',
            name='type',
            field=models.CharField(choices=[('c', 'char'), ('t', 'text'), ('u', 'link'), ('e', 'email'), ('p', 'phone')], max_length=2),
        ),
    ]
