# Generated by Django 2.1.5 on 2020-01-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0022_auto_20200119_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='use_case',
            field=models.CharField(choices=[('c', 'Tandora Changelog'), ('s', 'Tandora Web builder')], default='c', max_length=1),
        ),
    ]
