# Generated by Django 2.1.5 on 2020-01-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0023_auto_20200123_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='extra_plan_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
