# Generated by Django 2.1.5 on 2020-01-24 14:52

from django.db import migrations, models


def set_active_for_existing_users(apps, schema_editor):
    apps.get_model('v1', 'User').objects.all().update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0024_subscription_extra_plan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_active_for_existing_users),
    ]
