# Generated by Django 2.1.5 on 2020-01-24 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import v1.accounts.models
import v1.utils


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0025_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=v1.utils.random_uuid)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
