# Generated by Django 2.1.5 on 2020-02-09 05:44

from django.db import migrations, models
import django.db.models.deletion
import v1.utils


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0027_inlineimageattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('api_key', models.UUIDField(default=v1.utils.random_uuid)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Company')),
            ],
        ),
    ]
