# Generated by Django 2.1.5 on 2020-02-09 10:47

from django.db import migrations, models
import v1.utils


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0028_zapier'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapier',
            name='zapier_webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zapier',
            name='api_key',
            field=models.UUIDField(db_index=True, default=v1.utils.random_uuid),
        ),
    ]
