# Generated by Django 2.1.5 on 2020-02-12 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0029_auto_20200209_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZapierWebhookTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('zapier_response_status_code', models.PositiveIntegerField()),
                ('zapier_response', models.TextField()),
                ('changelog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Changelog')),
            ],
        ),
        migrations.AddField(
            model_name='zapier',
            name='zapier_trigger_scenario',
            field=models.CharField(choices=[('pu', 'Whenever a changelog is published for the first time'), ('ne', 'Whenever a changelog is created whether it is published or not')], default='ne', help_text='When to trigger the zapier webhook?', max_length=2),
        ),
        migrations.AddField(
            model_name='zapierwebhooktrigger',
            name='zapier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Zapier'),
        ),
    ]
