# Generated by Django 2.1.5 on 2020-02-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0030_auto_20200212_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embed',
            options={'verbose_name': 'Embed Widget', 'verbose_name_plural': 'Embed Widget'},
        ),
        migrations.AlterField(
            model_name='embed',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='embed',
            name='javascript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
