# Generated by Django 2.1.5 on 2020-02-16 03:23

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0031_auto_20200215_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicpage',
            name='private_mode',
        ),
        migrations.RemoveField(
            model_name='publicpage',
            name='show_authors',
        ),
        migrations.AddField(
            model_name='publicpage',
            name='_settings',
            field=models.TextField(blank=True, db_column='settings', null=True),
        ),
        migrations.AlterField(
            model_name='publicpage',
            name='color',
            field=colorful.fields.RGBColorField(default='#428bca'),
        ),
        migrations.AlterField(
            model_name='publicpage',
            name='hide_from_crawlers',
            field=models.BooleanField(default=True),
        ),
    ]
