# Generated by Django 2.1.5 on 2020-02-16 03:59
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def update_domain_in_site(apps, schema_editor):
    try:
        site_model = apps.get_model('sites', 'Site')
        site = site_model.objects.get()
        host = settings.HOST[:-1] if settings.HOST.endswith('/') else settings.HOST
        host = host.replace('https://', '')
        site.domain = host
        site.name = 'Tandora'
        site.save()
    except Exception as e:
        print(e.__repr__())
        return


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0032_auto_20200216_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicpage',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Company'),
        ),
        migrations.RunPython(update_domain_in_site),
    ]
