# Generated by Django 2.1.5 on 2020-02-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0033_auto_20200216_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicpage',
            name='_settings',
        ),
        migrations.AddField(
            model_name='publicpage',
            name='company_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='publicpage',
            name='font',
            field=models.CharField(choices=[('https://fonts.googleapis.com/css?family=Gelasio&display=swap', 'Gelasio'), ('https://fonts.googleapis.com/css?family=Gupter&display=swap', 'Gupter'), ('https://fonts.googleapis.com/css?family=Lato&display=swap', 'Lato'), ('https://fonts.googleapis.com/css?family=Lilita+One&display=swap', 'Lilita One'), ('https://fonts.googleapis.com/css?family=Montserrat&display=swap', 'Montserrat'), ('https://fonts.googleapis.com/css?family=Open+Sans&display=swap', 'Open Sans'), ('https://fonts.googleapis.com/css?family=Oswald&display=swap', 'Oswald'), ('https://fonts.googleapis.com/css?family=Playfair+Display&display=swap', 'Playfair Display'), ('https://fonts.googleapis.com/css?family=Poppins&display=swap', 'Poppins'), ('https://fonts.googleapis.com/css?family=Roboto&display=swap', 'Roboto'), ('https://fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap', 'Source Sans Pro')], default='https://fonts.googleapis.com/css?family=Lato&display=swap', max_length=100),
        ),
        migrations.AddField(
            model_name='publicpage',
            name='tag_line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicpage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
