# Generated by Django 2.1.5 on 2020-03-08 03:44

from django.db import migrations

from v1.accounts.models import Company


def add_is_first_login_to_company_settings(apps, schema_editor):
    for company in Company.objects.all():
        settings = company.settings
        settings['is_first_login'] = False
        company.settings = settings
        company.save()


class Migration(migrations.Migration):
    dependencies = [
        ('v1', '0033_auto_20200216_0359'),
    ]

    operations = [
        migrations.RunPython(add_is_first_login_to_company_settings)
    ]
