# Generated by Django 2.1.5 on 2020-03-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0034_auto_20200308_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='custom_url_path',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
    ]
