# Generated by Django 2.1.5 on 2020-03-09 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0035_changelog_custom_url_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='changelog',
            unique_together={('company', 'custom_url_path')},
        ),
    ]
