# Generated by Django 2.1.5 on 2020-03-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0036_auto_20200309_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
