# Generated by Django 2.1.5 on 2020-03-14 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0038_auto_20200314_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embed',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Company'),
        ),
    ]
