# Generated by Django 2.1.5 on 2020-04-04 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0039_auto_20200314_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticsitetheme',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.Company'),
        ),
        migrations.AddField(
            model_name='staticsitetheme',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
