# Generated by Django 2.1.5 on 2020-04-04 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0040_auto_20200404_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticsitetheme',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.Company'),
        ),
    ]
