# Generated by Django 2.1.5 on 2020-04-12 04:27

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0041_auto_20200404_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicpage',
            old_name='color',
            new_name='banner_color',
        ),
        migrations.AddField(
            model_name='publicpage',
            name='banner_font_color',
            field=colorful.fields.RGBColorField(default='#FFFFFF'),
        ),
        migrations.AddField(
            model_name='publicpage',
            name='font',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicpage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='publicpage',
            name='hide_from_crawlers',
            field=models.BooleanField(default=True, help_text="Check this option, if you don't want your page to be indexed by search engines."),
        ),
    ]
