# Generated by Django 2.1.5 on 2020-04-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0042_auto_20200412_0427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicpage',
            options={'verbose_name': 'Public Page Settings', 'verbose_name_plural': 'Public Page Settings'},
        ),
        migrations.RemoveField(
            model_name='publicpage',
            name='_settings',
        ),
        migrations.AddField(
            model_name='publicpage',
            name='changelog_limit',
            field=models.IntegerField(default=10, help_text='Maximum number of changelogs to show in public page. (Minimum  10 Maximum 50)'),
        ),
    ]
