# Generated by Django 2.1.5 on 2020-04-19 04:31

import django.core.validators
from django.db import migrations, models
import v1.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0043_auto_20200419_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicpage',
            name='changelog_limit',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of changelogs to show in public page. (Minimum  10 Maximum 50)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='publicpage',
            name='logo',
            field=models.ImageField(blank=True, help_text='Max file size: 500 kb', null=True, upload_to='', validators=[v1.utils.validators.validate_logo]),
        ),
    ]
