# Generated by Django 2.1.5 on 2020-04-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0044_auto_20200419_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpage',
            name='banner_tag_line',
            field=models.CharField(blank=True, help_text='(Optional) If not provided, changelog terminology will be used.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicpage',
            name='banner_title',
            field=models.CharField(blank=True, help_text='(Optional) If not provided, company name will be used.', max_length=50, null=True),
        ),
    ]
