# Generated by Django 2.1.5 on 2020-04-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0045_auto_20200419_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embed',
            name='color',
        ),
    ]
