# Generated by Django 2.1.5 on 2020-04-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0046_remove_embed_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='hide_banner',
            field=models.BooleanField(default=True, help_text="Enable this if you don't want the banner to be shown in widget."),
        ),
    ]
