# Generated by Django 2.1.5 on 2020-07-24 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0047_embed_hide_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=20)),
                ('resource_id', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=10)),
                ('performed_by', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=50)),
                ('payload', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='use_case',
            field=models.CharField(choices=[('c', 'Tandora Changelog')], default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.Company'),
        ),
    ]
