# Generated by Django 2.1.5 on 2020-05-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0048_subscription_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=50)),
                ('short_url', models.URLField(max_length=50)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Company')),
            ],
        ),
    ]
