# Generated by Django 2.1.5 on 2020-08-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0048_auto_20200724_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
