# Generated by Django 3.1.2 on 2020-10-25 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0048_subscription_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=50)),
                ('short_url', models.URLField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.priceplan')),
            ],
        ),
    ]
