# Generated by Django 2.1.5 on 2020-05-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0049_auto_20200819_0515'),
    ]
    operations = [
        migrations.AddField(
            model_name='subscription',
            name='invoice_id',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
