# Generated by Django 3.1.2 on 2020-10-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0049_pendinginvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='invoice_id',
            field=models.CharField(default='NA', max_length=60),
        ),
    ]
