# Generated by Django 3.1.2 on 2020-10-26 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0049_auto_20200819_0515'),
        ('v1', '0049_pendinginvoice'),
    ]

    operations = [
    ]
