# Generated by Django 3.1.2 on 2021-04-24 05:26

from django.db import migrations, models
import django.db.models.deletion
import payanpaadu.utils


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0050_merge_20201026_0237'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='changelog',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Webhooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('key', models.CharField(default=payanpaadu.utils.get_key, max_length=32)),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('trigger_event', models.CharField(choices=[('pu', 'Whenever a changelog is published for the first time'), ('ne', 'Whenever a changelog is created whether it is published or not')], max_length=2)),
                ('categories', models.ManyToManyField(to='v1.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(default='{}')),
                ('status_code', models.IntegerField()),
                ('response', models.TextField(default='{}')),
                ('trigger_time', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=32)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.webhooks')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='custom_url_path',
        ),
    ]
