# Generated by Django 3.1.2 on 2021-04-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0051_auto_20210424_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooks',
            name='trigger_event',
        ),
        migrations.AddField(
            model_name='webhooks',
            name='trigger_when_created',
            field=models.BooleanField(default=False, help_text='Whenever a changelog is created whether it is published or not'),
        ),
        migrations.AddField(
            model_name='webhooks',
            name='trigger_when_published',
            field=models.BooleanField(default=False, help_text='Whenever a changelog is published for the first time'),
        ),
    ]
