# Generated by Django 3.1.2 on 2021-04-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0052_auto_20210424_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooks',
            name='categories',
        ),
    ]
