# Generated by Django 3.1.2 on 2021-04-24 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0053_remove_webhooks_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooks',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.company'),
        ),
    ]
