# Generated by Django 3.1.2 on 2021-05-18 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0054_auto_20210424_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('access_token', models.CharField(max_length=100)),
                ('access_token_secret', models.CharField(max_length=100)),
                ('consumer_key', models.CharField(max_length=100)),
                ('consumer_secret', models.CharField(max_length=100)),
                ('tweet_content', models.CharField(default='\nModify this tweet as per your requirement.\nYou can use the following variables that will reference the changelog.\n{title}\n{content}\n{category}\n{link}\nPlease use the above variables in your tweet content which will get substituted with the changelog values.\n', max_length=280)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.company')),
            ],
        ),
    ]
