# Generated by Django 3.1.2 on 2021-05-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0055_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter',
            name='trigger_when_created',
            field=models.BooleanField(default=False, help_text='Whenever a changelog is created whether it is published or not'),
        ),
        migrations.AddField(
            model_name='twitter',
            name='trigger_when_published',
            field=models.BooleanField(default=False, help_text='Whenever a changelog is published for the first time'),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='tweet_content',
            field=models.TextField(default='\nModify this tweet as per your requirement.\nYou can use the following variables that will reference the changelog.\n{title}\n{content}\n{category}\n{link}\nPlease use the above variables in your tweet content which will get substituted with the changelog values.\n', max_length=280),
        ),
    ]
