# Generated by Django 3.1.2 on 2021-05-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0056_auto_20210518_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitter',
            old_name='trigger_when_created',
            new_name='tweet_when_created',
        ),
        migrations.RenameField(
            model_name='twitter',
            old_name='trigger_when_published',
            new_name='tweet_when_published',
        ),
    ]
