# Generated by Django 3.1.2 on 2021-09-10 17:49

from django.db import migrations, models
import v1.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0057_auto_20210518_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[v1.utils.validators.validate_image_size]),
        ),
    ]
