# Generated by Django 3.1.2 on 2021-09-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0058_changelog_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticsitetheme',
            name='company',
        ),
        migrations.RemoveField(
            model_name='staticsitethemeconfig',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='staticsitethemeconfig',
            name='theme',
        ),
        migrations.DeleteModel(
            name='StaticSiteField',
        ),
        migrations.DeleteModel(
            name='StaticSiteTheme',
        ),
        migrations.DeleteModel(
            name='StaticSiteThemeConfig',
        ),
    ]
