# Generated by Django 3.1.2 on 2021-09-14 06:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0059_auto_20210910_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.company')),
            ],
        ),
        migrations.CreateModel(
            name='Slack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('channel_to_post', models.CharField(default='#random', max_length=100)),
                ('oauth_response', models.JSONField(default={})),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.company')),
            ],
        ),
    ]
