# Generated by Django 3.1.2 on 2021-09-14 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0060_slack_slackstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slack',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.company'),
        ),
    ]
