# Generated by Django 3.1.2 on 2021-09-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0061_auto_20210914_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='slack',
            name='trigger_when_created',
            field=models.BooleanField(default=False, help_text='Whenever a changelog is created whether it is published or not'),
        ),
        migrations.AddField(
            model_name='slack',
            name='trigger_when_published',
            field=models.BooleanField(default=False, help_text='Whenever a changelog is published for the first time'),
        ),
    ]
