# Generated by Django 3.1.2 on 2021-09-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0062_auto_20210914_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slack',
            name='oauth_response',
            field=models.JSONField(default=dict),
        ),
    ]
