# Generated by Django 3.1.2 on 2021-10-23 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0063_auto_20210914_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='reference_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.affiliate'),
        ),
    ]
