# Generated by Django 3.1.2 on 2021-10-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0064_auto_20211023_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='is_app_sumo_code',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_used',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
