# Generated by Django 3.1.2 on 2021-10-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0065_auto_20211023_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='is_app_sumo_code',
        ),
    ]
