# Generated by Django 3.1.2 on 2021-10-27 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0066_remove_referral_is_app_sumo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedChangelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changelog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.changelog')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.company')),
            ],
        ),
    ]
