# Generated by Django 3.1.2 on 2021-10-27 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0067_pinnedchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedchangelog',
            name='changelog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.changelog'),
        ),
    ]
