# Generated by Django 3.1.2 on 2021-10-27 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0068_auto_20211027_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedchangelog',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.company'),
        ),
    ]
