# Generated by Django 3.1.2 on 2021-12-05 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0069_auto_20211027_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(unique=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.company')),
            ],
        ),
    ]
