# Generated by Django 3.1.2 on 2021-12-18 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0070_sitemapdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title_mapping', models.CharField(max_length=50)),
                ('content_mapping', models.CharField(max_length=50)),
                ('published_mapping', models.CharField(blank=True, max_length=50, null=True)),
                ('published_value', models.BooleanField(default=True, help_text='If published mapping is not set, then this will be given preference when creating changelog to decide whether it should be published or not.')),
                ('featured_image_mapping', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.company')),
            ],
        ),
    ]
