# Generated by Django 3.1.2 on 2021-12-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0071_incomingwebhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingwebhook',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.category'),
        ),
    ]
