# Generated by Django 3.1.2 on 2021-12-18 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0072_auto_20211218_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingwebhook',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
