# Generated by Django 3.1.2 on 2021-12-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0073_incomingwebhook_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingWebhookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(default='{}')),
                ('status_code', models.IntegerField()),
                ('response', models.TextField(default='{}')),
                ('trigger_time', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=32)),
                ('incoming_webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.incomingwebhook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
