# Generated by Django 3.1.2 on 2021-12-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0074_incomingwebhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_sitemap',
            field=models.BooleanField(default=False),
        ),
    ]
