# Generated by Django 3.1.2 on 2021-12-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0075_company_custom_sitemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpage',
            name='seo_title',
            field=models.CharField(blank=True, help_text='(Optional) This will used to inform search engines about the content and keywords of your public page.', max_length=200, null=True),
        ),
    ]
