# Generated by Django 3.1.2 on 2021-12-22 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0076_publicpage_seo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PublicPageViewAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, max_length=250, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('public_page_view', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='v1.publicpageview')),
            ],
        ),
    ]
