# Generated by Django 3.1.2 on 2022-01-21 07:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0078_auto_20211222_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_append_content', tinymce.models.HTMLField(blank=True, help_text='This content will be automatically added to the end of each changelog you create.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.company')),
            ],
        ),
    ]
