# Generated by Django 3.1.2 on 2022-01-25 07:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0079_changelogsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelogsettings',
            options={'verbose_name_plural': 'Changelog Settings'},
        ),
        migrations.AlterField(
            model_name='changelogsettings',
            name='auto_append_content',
            field=tinymce.models.HTMLField(blank=True, help_text='This content will be automatically added to the end of each changelog you create.This content will be visible only in public changelog details page.'),
        ),
        migrations.AlterUniqueTogether(
            name='forgotpassword',
            unique_together=set(),
        ),
    ]
