# Generated by Django 3.1.2 on 2022-08-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0083_linklens'),
    ]

    operations = [
        migrations.AddField(
            model_name='linklens',
            name='device_type',
            field=models.CharField(blank=True, choices=[('mo', 'Mobile'), ('tb', 'Tablet'), ('pc', 'Laptop/Desktop/Personal Computer'), ('bo', 'Bot')], max_length=2, null=True),
        ),
    ]
