# Generated by Django 3.1.2 on 2022-08-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0084_linklens_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linklens',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
