# Generated by Django 3.1.2 on 2022-08-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0085_auto_20220807_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
