# Generated by Django 3.1.2 on 2022-08-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0087_auto_20220807_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_domain',
            field=models.URLField(blank=True, null=True),
        ),
    ]
